name: musicapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  audio_service: ^0.18.12
  flutter:
    sdk: flutter
  get: ^4.6.6
  on_audio_query: ^2.9.0
  transparent_image: ^2.0.1
  just_audio: ^0.9.35
  permission_handler: ^11.0.1
  audio_video_progress_bar: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
